sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

matrix:
  include:
    - {python: "3.6", env: TOXENV=packaging}

install:
  - pip install tox tox-travis tox-venv
  - pip install coveralls
script: tox
after_success:
  - coveralls
